run:
  timeout: 10m

linters:
  enable:
    - bodyclose
    - gofmt
    - goimports
    - revive
    - gosec
    - misspell
    - unconvert
    - unparam

linters-settings:
  misspell:
    ignore-words:
      - clas
      - cancelled
    locale: US
  gofmt:
    simplify: true
  unparam:
    check-exported: false

issues:
  exclude:
    # TODO(jpeach): exclude unparam warnings about functions that always receive
    # the same arguments. We should clean those up some time.
    - always receives
  exclude-rules:
    - path: zz_generated
      linters:
        - goimports
    # TODO(youngnick): Disable the deprecation warnings, because of the "github.com/golang/protobuf/proto"
    # libraries. We can't stop using them yet, because they move from Proto v1 to V2
    # And we can't nolint them by line, because https://github.com/golangci/golangci-lint/issues/741
    - linters:
        - golint
      text: "returns unexported type"
    - linters:
        - golint
      text: "don't use ALL_CAPS in Go names; use CamelCase"
