apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: contour-operator
  name: contour-operator-metrics
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: contour-operator
