# permissions for end users to view contours.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contour-viewer
rules:
- apiGroups:
  - operator.projectcontour.io
  resources:
  - contours
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.projectcontour.io
  resources:
  - contours/status
  verbs:
  - get
