name: Build and Test

# Trigger the workflow on push or pull request
on: [push, pull_request]

env:
  GOPROXY: https://proxy.golang.org/
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: deps
        run: |
          ./hack/install-kubernetes-toolchain.sh $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
      - name: test
        run: |
          go mod vendor
          make local-cluster install test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          only-new-issues: true
