name: Build and Test

# Trigger the workflow on push or pull request
on:
   # Run every hour
  schedule:
    - cron: '0 * * * *'
  push:
  pull_request:

env:
  GOPROXY: https://proxy.golang.org/
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.8'
      - name: deps
        run: |
          ./hack/actions/install-kubernetes-toolchain.sh $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
      - name: test
        run: |
          make test
  test-example-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.8'
      - name: deps
        run: |
          ./hack/actions/install-kubernetes-toolchain.sh $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
      - name: test-example
        run: |
          make local-cluster load-image example test-example
  test-e2e-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.8'
      - name: deps
        run: |
          ./hack/actions/install-kubernetes-toolchain.sh $GITHUB_WORKSPACE/bin
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH
      - name: test-e2e
        run: |
          make local-cluster load-image test-e2e
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git,./vendor,go.*
          ignore_words_file: './.codespell.ignorewords'
          check_filenames: true
          check_hidden: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
          only-new-issues: true
